version: '3.8'

services:
  backend:
    build:
      context: https://github.com/avantikasistemas/backend_macroeconomicas.git#master
      dockerfile: Dockerfile
    container_name: macroeconomicas-backend
    ports:
      - "8002:8002"
    environment:
      - DRIVER=${DRIVER}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - ENCRYPT=${ENCRYPT}
      - TRUST_CERTIFICATE=${TRUST_CERTIFICATE}
      - MY_SECRET_KEY=${MY_SECRET_KEY}
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: https://github.com/avantikasistemas/frontend_macroeconomicas.git#master
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://130.1.1.7:8002
        - CACHEBUST=${CACHEBUST:-1}
    container_name: macroeconomicas-frontend
    ports:
      - "5177:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
